const vXSspacing = 4;
const vSspacing = 8;
const vMspacing = 16;
const vLspacing = 32;
const vXLspacing = 48;
const vXXLspacing = 64;

const List<String> lodzStreets = [
  "Ketlinga",
  "Kieratowa",
  "Kierowa",
  "Kierpcowa",
  "Kierunkowa",
  "Kijanki",
  "Kirasjerów",
  "Klaretyńska",
  "Klasowa",
  "Klasyczna",
  "Klasztorna",
  "Kleeberga",
  "Klimatyczna",
  "Klinowa",
  "Kłodzka",
  "Kłosowa",
  "Klubowa",
  "Kluczowa",
  "Kmicica",
  "Kobaltowa",
  "Kobzowa",
  "Kogucia",
  "Kokosowa",
  "Kolarska",
  "Kolejowa",
  "Kolektywna",
  "Kolińskiego",
  "Kołobrzeska",
  "Kołodziejska",
  "Kolorowa",
  "Kołowa",
  "Kolumny",
  "Komandorska",
  "Komandosów",
  "Komfortowa",
  "Kominiarska",
  "Kominowa",
  "Kompostowa",
  "Komputerowa",
  "Komunalna",
  "Komunardów",
  "Konarowa",
  "Koncertowa",
  "Konfederatów Barskich",
  "Koniakowska",
  "Koniczynowa",
  "Konna",
  "Konopna",
  "Konspiracji",
  "Konstantego Ildefonsa Gałczyńskiego",
  "Konstantynowska",
  "Konstytucyjna",
  "Konwaliowa",
  "Kopalniana",
  "Kopernika",
  "Koprowa",
  "Koralowa",
  "Koronna",
  "Korsaka",
  "Korsarska",
  "Korsykańska",
  "Koryncka",
  "Korzeniowskiego",
  "Korzenna",
  "Kościelna",
  "Kosmiczna",
  "Kosmonautów",
  "Kosodrzewiny",
  "Kossaka",
  "Kosynierów Gdyńskich",
  "Koszalińska",
  "Koszykowa",
  "Kotarbińskiego",
  "Kotoniarska",
  "Kotwiczna",
  "Kowalska",
  "Kowalszczyzna",
  "Kowieńska",
  "Kownackiej",
  "Kozia",
  "Kozielska",
  "Koźmiana",
  "Krajobrazowa",
  "Krajowa",
  "Krakowska",
  "Krakusa",
  "Krańcowa",
  "Krasnoludków",
  "Kraszewskiego",
  "Kraterowa",
  "Krawiecka",
  "Krecia",
  "Kresowa",
  "Kresowych Stanic",
  "Krochmalna",
  "Krokiew",
  "Krokusowa",
  "Króla Boleslawa Chrobrego",
  "Królewska",
  "Królowej Anny Jagiellonki",
  "Kronikarska",
  "Krośnieńska",
  "Krótka",
  "Krotoszyńska",
  "Krucza",
  "Kruczkowskiego",
  "Krupówki",
  "Kruszynowa",
  "Krynicka",
  "Kryształowa",
  "Kryzysowa",
  "Krzemieniecka",
  "Krzemieniowa",
  "Krzeptowskiego",
  "Krzewowa",
  "Krzywa",
  "Krzywickiego",
  "Krzyżowa",
  "Ksawerowska",
  "Księcia Janusza Mazowieckiego",
  "Księcia Władysława Opolczyka",
  "Księdza Biskupa Wincentego Tymienieckiego",
  "Księdza Hugona Kołłątaja",
  "Księdza Piotra Skargi",
  "Księdza Stanisława Staszica",
  "Księdza Wojciecha Jakubowicza",
  "Księżnej Kingi",
  "Księżycowa",
  "Kubusia Puchatka",
  "Kujawska",
  "Kupały",
  "Kurantowa",
  "Kurczaki",
  "Kuropatwia",
  "Kusa",
  "Kusocińskiego",
  "Kutnowska",
  "Kutrowa",
  "Kuźnicka",
  "Kwarcowa",
  "Kwartalna",
  "Kwaterunkowa",
  "Kwiatowa",
  "Kwiatów Polskich",
  "Kwidzyńska",
  "Kwiecista",
  "Kwietniowa",
  "Łagiewnicka",
  "Lajkonika",
  "Łąkowa",
  "Langiewicza",
  "Laserowa",
  "Laskowa",
  "Laskowicka",
  "Latawcowa",
  "Laurowa",
  "Lawendowa",
  "Lawinowa",
  "Lazurowa",
  "Lęborska",
  "Lechicka",
  "Lechosława Roszkowskiego",
  "Lecznicza",
  "Łęczycka",
  "Legionów",
  "Legnicka",
  "Lelewela",
  "Lemieszowa",
  "Lenartowicza",
  "Lermontowa",
  "Leśmiana",
  "Leśna",
  "Leszczowa",
  "Leszczynowa",
  "Leszka Białego",
  "Letniskowa",
  "Lewa",
  "Lewarowa",
  "Leżakowa",
  "Libijska",
  "Liczyrzepy",
  "Liliowa",
  "Limanowskiego",
  "Limbowa",
  "Liniowa",
  "Lipowa",
  "Liryczna",
  "Liściasta",
  "Listopadowa",
  "Litewska",
  "Lniana",
  "Lodowa",
  "Lokatorska",
  "Lontowa",
  "Lorentza",
  "Lotna",
  "Lotnicza",
  "Lubelska",
  "Lublinek",
  "Lubuska",
  "Lucjana Rydla",
  "Lucjana Szenwalda",
  "Ludowa",
  "Ludwika Zamenhofa",
  "Łukasińskiego",
  "Luksemburska",
  "Luźna",
  "Macieja Boryny",
  "Maciejewskiego",
  "Maciejkowa",
  "Maciejowicka",
  "Macierzanki",
  "Maćka z Bogdańca",
  "Mackiewicza",
  "Maczka",
  "Magazynowa",
  "Magdaleny",
  "Magnesowa",
  "Magnoliowa",
  "Mahoniowa",
  "Majewskiego",
  "Majora Józefa Oxińskiego",
  "majora Zygmunta Szendzielarza „Łupaszki”",
  "Majowa",
  "Maksyma Gorkiego",
  "Makuszyńskiego",
  "Mała",
  "Malachitowa",
  "Malarska",
  "Malborska",
  "Malczewskiego",
  "Małego Rycerza",
  "Malinowa",
  "Małopolska",
  "Malownicza",
  "Maltańska",
  "Malwowa",
  "Manewrowa",
  "Mania",
  "Maratońska",
  "Marcina",
  "Marcina Kasprzaka",
  "Marciniaka",
  "Marczyńskich",
  "Margaretek",
  "Mariana Cynarskiego",
  "Mariana Raciborskiego",
  "Marii",
  "Marii Konopnickiej",
  "Marii Piotrowiczowej",
  "Marii Wedmanowej",
  "Marmurowa",
  "Marszowa",
  "Marynarska",
  "Marynarzy Polskich",
  "Marysińska",
  "Marzanny",
  "Masłochów",
  "Masztowa",
  "Maszynowa",
  "Mateusza",
  "Matowa",
  "Mazowiecka",
  "Mazurska",
  "Mechaniczna",
  "Melchiora Wańkowicza",
  "Mencla",
  "Metalowa",
  "Mewy",
  "Mglista",
  "Miarki",
  "Michała",
  "Michała Bałuckiego",
  "Michała Drzymały",
  "Michała Wołodyjowskiego",
  "Michałowicza",
  "Michałowska",
  "Micińskiego",
  "Miechowska",
  "Mieczników",
  "Mieczysława Brauna",
  "Mieczysława Jagoszewskiego",
  "Mieczysława Karłowicza",
  "Miedziana",
  "Międzyrzecze",
  "Miejska",
  "Mielizny",
  "Miernicza",
  "Mierzejowa",
  "Mierzyńskiego",
  "Mieszczańska",
  "Mieszkalna",
  "Mieszka I",
  "Miętowa",
  "Migdałowa",
  "Mikołaja Gogola",
  "Mikołaja Reja",
  "Mikowa",
  "Miła",
  "Mileszki",
  "Milionowa",
  "Mimozy",
  "Mineralna",
  "Minerska",
  "Miniaturowa",
  "Mińska",
  "Miodowa",
  "Mirabelki",
  "Mirtowa",
  "Młynarska",
  "Mocarna",
  "Mochnackiego",
  "Mocna",
  "Moczarowa",
  "Modra",
  "Modrzejewskiej",
  "Modrzewiowa",
  "Mohandasa Gandhiego",
  "Molla",
  "Moniuszki",
  "Morawska",
  "Morcinka",
  "Morelowa",
  "Morenowa",
  "Morgowa",
  "Morska",
  "Morskie Oko",
  "Morwowa",
  "Mosiężna",
  "Moskule",
  "Moskuliki",
  "Motorowa",
  "Motylowa",
  "Mozaikowa",
  "Mrówcza",
  "Mroźna",
  "Mulinowicza",
  "Mundurowa",
  "Municypalna",
  "Murarska",
  "Murawy",
  "Muszkieterów",
  "Muszlowa",
  "Musztrowa",
  "Mylna",
  "Myśliwska",
  "Mysłowicka",
  "Nadwodna",
  "Nad Jasieniem",
  "Nad Karolewką",
  "Nad Nerem",
  "Nad Niemnem",
  "Nad Sokołówką",
  "Nad Stawem",
  "Naftowa",
  "Nagietkowa",
  "Nałkowskiej",
  "Namiotowa",
  "Napoleońska",
  "Narciarska",
  "Narcyzowa",
  "Narewska",
  "Narodowa",
  "Naruszewicza",
  "Narutowicza",
  "Narwik",
  "Nasienna",
  "Nastrojowa",
  "Nasturcjowa",
  "Natalii",
  "Nawrot",
  "Na Uboczu",
  "Nefrytowa",
  "Nenckiego",
  "Nenufarowa",
  "Neonowa",
  "Nery",
  "Niciarniana",
  "Niecała",
  "Niedziałkowskiego",
  "Niemcewicza",
  "Niemena",
  "Niemojewskiego",
  "Niepołomicka",
  "Niesięcin",
  "Nieszawska",
  "Niezapominajki",
  "Niska",
  "Niwelacyjna",
  "Nizinna",
  "Niższa",
  "Normandzka",
  "Norwida",
  "Notecka",
  "Nowa",
  "Nowe Górki",
  "Nowe Sady",
  "Nowogrodzka",
  "Nowomiejska",
  "Nowopolska",
  "Nowożeńców",
  "Nurkowa",
  "Nurta-Kaszyńskiego",
  "Oazowa",
  "Objazdowa",
  "Oblęgorska",
  "Obłoczna",
  "Obornicka",
  "Obozowa",
  "Obrońców Warszawy",
  "Obrońców Westerplatte",
  "Obronna",
  "Obszerna",
  "Obwodowa",
  "Obywatelska",
  "Odolanowska",
  "Odolanowska 8",
  "Odrzańska",
  "Odważna",
  "Odyńca",
  "Ofiarna",
  "Ogińskiego",
  "Ogniskowa",
  "Ogórkowa",
  "Ogrodnicza",
  "Ogrodowa",
  "Okienna",
  "Okólna",
  "Okoniowa",
  "Okopowa",
  "Okręglik",
  "Okręgowa",
  "Okrętowa",
  "Okrężna",
  "Okrzei",
  "Oksywie",
  "Okulickiego",
  "Olechowska",
  "Olimpijska",
  "Oliwkowa",
  "Oliwska",
  "Olkuska",
  "Ołowiana",
  "Olsztyńska",
  "Omłotowa",
  "Onyksowa",
  "Opalowa",
  "Opiekuńcza",
  "Opoczyńska",
  "Opolska",
  "Oppmana",
  "Organizacji „Wolność i Niezawisłość”",
  "Orkana",
  "Orłowska",
  "Ormiańska",
  "Orna",
  "Orzelskiej",
  "Orzeszkowej",
  "Osadnicza",
  "Osiedlowa",
  "Osinowa",
  "Oskardowa",
  "Osobliwa",
  "Ossowskiego",
  "Osterwy",
  "Ostowa",
  "Ostrołęcka",
  "Ostróżek",
  "Oświatowa",
  "Oświęcimska",
  "Oszczepowa",
  "Owcza",
  "Owocowa",
  "Owsiana",
  "Ozdobna",
  "Ozorkowska",
  "Pabianicka",
  "Pabianka",
  "Paderewskiego",
  "Pałacowa",
  "Palmowa",
  "Pancerna",
  "Pancerniaków",
  "Panoramiczna",
  "Pańska",
  "Papiernicza",
  "Paprociowa",
  "Paradna",
  "Parafialna",
  "Parcelacyjna",
  "Parkowa",
  "Parowozowa",
  "Partyzantów",
  "Paryska",
  "Pasieczna",
  "Pasjansowa",
  "Pastelowa",
  "Pasterska",
  "Patrice Lumumby",
  "Patriotyczna",
  "Pawia",
  "Pawilońska",
  "Pawła",
  "Peoniowa",
  "Perla",
  "Perlicza",
  "Perłowa",
  "Peron 2",
  "Piaseczna",
  "Piaskowa",
  "Piaskowiec",
  "Piasta",
  "Piasta Kołodzieja",
  "Piechala",
  "Piechura",
  "Piekarska",
  "Piękna",
  "Pieniny",
  "Pienista",
  "Pierwiosnków",
  "Pieśni Rycerskiej",
  "Piesza",
  "Pietrusińskiego",
  "Pikowa",
  "Piliczna",
  "Piłkarska",
  "Pilotów",
  "Pilska",
  "Piłsudskiego",
  "Piołunowa",
  "Pionierska",
  "Piotrkowska",
  "Piramowicza",
  "Pirytowa",
  "Pisankowa",
  "Pisarska",
  "Pistacjowa",
  "Piwna",
  "Piwnika",
  "Piwowarska",
  "Placowa",
  "plac Komuny Paryskiej",
  "Planetarna",
  "Plantowa",
  "Płaska",
  "Plastyczna",
  "Płatowcowa",
  "Platynowa",
  "Plażowa",
  "Plenerowa",
  "Płocka",
  "Płomienna",
  "Plonowa",
  "Pługowa",
  "Płynna",
  "Płytka",
  "Pływacka",
  "Pocztowa",
  "Podbiałowa",
  "Podbipięty",
  "Podchorążych",
  "Podgórna",
  "Podhalańska",
  "Podjazdowa",
  "Podleśna",
  "Podmiejska",
  "Podmokła",
  "Podrzeczna",
  "Podwale",
  "Poetycka",
  "Pogodna",
  "Pogorzel",
  "Pograniczna",
  "Pojezierska",
  "Pokładowa",
  "Pokojowa",
  "Pola",
  "Polarna",
  "Policyjna",
  "Poli Gojawiczyńskiej",
  "Polna",
  "Północna",
  "Połoniny",
  "Polskich Kolei Państwowych",
  "Polskiej Organizacji Wojskowej",
  "Pomarańczowa",
  "Pomidorowa",
  "Pomorska",
  "Poniatowskiego",
  "Pontonowa",
  "Popiela",
  "Popiełuszki",
  "Popioły",
  "Popowskiego",
  "Poprzeczna",
  "Popularna",
  "Poranna",
  "Porazińskiej",
  "Porfirowa",
  "Poronińska",
  "Portowa",
  "Porucznika Bronisława Skury-Skoczyńskiego „Robotnika”",
  "Porzeczkowa",
  "Poselska",
  "Postępowa",
  "Posucha",
  "Potokowa",
  "Potulna",
  "Powiatowa",
  "Powojowa",
  "Powolna",
  "Powstańców Śląskich",
  "Powstańców Wielkopolskich",
  "Powszechna",
  "Powtórna",
  "Pozioma",
  "Poziomkowa",
  "Poznańska",
  "Prądzyńskiego",
  "Praska",
  "Praussa",
  "Prezydenta",
  "Prezydenta Gabriela Narutowicza",
  "Prochowa",
  "Produkcyjna",
  "Profesorska",
  "Profesor Edwarda Rosseta",
  "Profesor Włodzimierza Musiała",
  "Profilowa",
  "Proletariacka",
  "Promienna",
  "Promowa",
  "Prośnieńska",
  "Prosta",
  "Prożka",
  "Próżna",
  "Prusa",
  "Prymulkowa",
  "Pryncypalna",
  "Przechodnia",
  "Przecława Smolika",
  "Przedborska",
  "Przednia",
  "Przedświt",
  "Przedszkolna",
  "Przedwiośnie",
  "Przędzalniana",
  "Przejściowa",
  "Przełajowa",
  "Przełęcz",
  "Przełomowa",
  "Przelotna",
  "Przepiórcza",
  "Przesmyk",
  "Przestrzenna",
  "Przewodnia",
  "Przewozowa",
  "Przodowników Pracy",
  "Przyborowskiego",
  "Przybosia",
  "Przybyszewskiego",
];
