name: landify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  google_fonts: 2.1.0
  flutter_screenutil: 5.0.1
  font_awesome_flutter: 9.2.0
  animated_text_kit: 4.2.1
  flutter_map: 0.14.0
  latlong: 0.6.1
  location: 4.3.0
  latlong2: 0.8.1
  invert_colors: 0.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

